#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely.
fkill()
{
    echo "I am invincible!!!"
}
trap "fkill" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
